services:
  evocelot-auth-service-liquibase:
    container_name: evocelot-auth-service-liquibase
    image: webdevops/liquibase:mysql
    command: ["update"]
    environment:
      LIQUIBASE_CONTEXTS: local
      LIQUIBASE_URL: jdbc:mariadb://evocelot-auth-service-mariadb:3306/auth
      LIQUIBASE_USERNAME: root
      LIQUIBASE_PASSWORD: admin
      LIQUIBASE_CHANGELOG: /liquibase/changelog/liquibase-auth-service-changelog.xml
      LIQUIBASE_DRIVER: org.mariadb.jdbc.Driver
    volumes:
      - ../changelog:/liquibase/changelog
networks:
  default:
    name: evocelot-network
